# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1026, 438)
        Dialog.setSizeGripEnabled(False)
        self.button_tx0 = QtWidgets.QPushButton(Dialog)
        self.button_tx0.setGeometry(QtCore.QRect(860, 310, 93, 28))
        self.button_tx0.setObjectName("button_tx0")
        self.table_tx = QtWidgets.QTableWidget(Dialog)
        self.table_tx.setGeometry(QtCore.QRect(220, 270, 621, 61))
        self.table_tx.setRowCount(1)
        self.table_tx.setColumnCount(10)
        self.table_tx.setObjectName("table_tx")
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_tx.setItem(0, 0, item)
        self.table_tx.horizontalHeader().setDefaultSectionSize(60)
        self.button_clr_tx = QtWidgets.QPushButton(Dialog)
        self.button_clr_tx.setGeometry(QtCore.QRect(860, 270, 93, 28))
        self.button_clr_tx.setObjectName("button_clr_tx")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(470, 240, 311, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lcdNumber_sec = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_sec.setGeometry(QtCore.QRect(60, 70, 251, 71))
        self.lcdNumber_sec.setDigitCount(8)
        self.lcdNumber_sec.setObjectName("lcdNumber_sec")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(490, 20, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.button_clr_rx = QtWidgets.QPushButton(Dialog)
        self.button_clr_rx.setGeometry(QtCore.QRect(860, 60, 93, 28))
        self.button_clr_rx.setObjectName("button_clr_rx")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(340, 60, 501, 161))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        self.button_clr_tx.clicked.connect(self.table_tx.clear)
        self.button_clr_rx.clicked.connect(self.listWidget.clear)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.button_tx0.setText(_translate("Dialog", "Transmit"))
        item = self.table_tx.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.table_tx.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Length"))
        item = self.table_tx.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "B0"))
        item = self.table_tx.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "B1"))
        item = self.table_tx.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "B2"))
        item = self.table_tx.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "B3"))
        item = self.table_tx.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "B4"))
        item = self.table_tx.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "B5"))
        item = self.table_tx.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "B6"))
        item = self.table_tx.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "B7"))
        __sortingEnabled = self.table_tx.isSortingEnabled()
        self.table_tx.setSortingEnabled(False)
        self.table_tx.setSortingEnabled(__sortingEnabled)
        self.button_clr_tx.setText(_translate("Dialog", "Clean content"))
        self.label_2.setText(_translate("Dialog", "CAN BUS Transmit (hex format)"))
        self.label_5.setText(_translate("Dialog", "CAN Received (hex format)"))
        self.button_clr_rx.setText(_translate("Dialog", "Clear all"))

